### ISSUE TITLE
可否对色块做一下大概介绍

### ISSUE THREAD

**Issue by movny** [jastoninfer/jastoninfer.github.io#1]
前面的这些是什么含义？
![image](https://user-images.githubusercontent.com/58254971/77733277-900a4a00-7041-11ea-8912-a722415a2796.png)
![image](https://user-images.githubusercontent.com/58254971/77733319-9f899300-7041-11ea-85ba-de7a38952f04.png)

**Comment by jastoninfer** [comment]
这些颜色表示学校属性类别，如双一流大学A/B类等。

**Comment by movny** [comment]
谢谢 如果有新版希望可以有个注释
